### ISSUE TITLE
!! Error evaluating 'gcode_macro BED_MESH_CALIBRATE:gcode': TypeError: bad operand type for abs(): 'str'

### ISSUE THREAD

**Issue by RocksaltX** [kyleisah/Klipper-Adaptive-Meshing-Purging#116]
**Describe the issue**
Message appears in console when bed mesh tried to start

**What slicer are you using?**
Superslicer

**Troubleshooting**
Came here :)

**Screenshots**

**Klipper log file:**
Please add klipper log file here...

**Sliced Gcode**
Please add sliced gcode file you are using here...

**Additional context**

**Comment by kyleisah** [comment]
klipper log please

**Comment by kyleisah** [comment]
I'm closing this becuase no klipper log was provided so I cannot diagnose the issue.
