### ISSUE TITLE
Mesh fails on thin long parts

### ISSUE THREAD

**Issue by MartijnGevaert** [kyleisah/Klipper-Adaptive-Meshing-Purging#124]
**Describe the issue**
The meshing fails on thin long parts, this makes it impossible to start the print for some parts. I have a part that is 0.9mm wide (2 layer lines). The meshing fails for this with following message:

bed_mesh: min/max points too close together

**What slicer are you using?**
Prusaslicer

**Troubleshooting**
What troubleshooting steps have you tried?

**Screenshots**
part:
![image](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/assets/41551215/20aee43e-048d-4eef-97dd-c0f14dc62b83)
klipper console:
![image](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/assets/41551215/d697eaab-a204-4b03-aaf8-4feea3d60149)

**Sliced Gcode**
Please add sliced gcode file you are using here...  -> Can't do, Github does not seem to allow this.

**Comment by kyleisah** [comment]
I think you might be using an old version of KAMP but that's not really related here. 

Were you testing the limits of KAMP or something? I purge more material than that 😂

**Comment by kyleisah** [comment]
This has actually come up a time or two before, I've been meaning to figure this out.

**Comment by kyleisah** [comment]
If you update to the newest KAMP, you can set a `mesh_margin` which will expand the object bounds by a set distance which should allow you to print objects as small as this.

**Comment by MartijnGevaert** [comment]
I was actually trying to replicate a bug I came across in Klipper. Hence the extreme geometry of the part.
I'll make sure to set up my mesh margin

**Comment by kyleisah** [comment]
Thanks for reaching out! I think you would be best just having a margin of 5 or more so even for these tiny parts, KAMP should be able to adapt.
