### ISSUE TITLE
FEATURE REQUEST ADAPTIVE Z-TILT (G34) 

### ISSUE THREAD

**Issue by BigWampa1989** [kyleisah/Klipper-Adaptive-Meshing-Purging#127]
It would be cool if this could also change the coordinates of Z-Tilt (G34 so that they were the farthest left and farthest right of the adaptive bed mesh.

**Comment by kyleisah** [comment]
Hey there! 

Unfortunately, klipper does not currently allow this. The probe points and pivot locations are something that cannot be changed during runtime, so adaptive leveling is not currently possible. 

Maybe some day!

**Comment by BigWampa1989** [comment]
I made a post on the Klipper site requesting they add that functionality.
Would be useful to have Z-Tilt squared specifically to the printing area
don't you think?

Best Regards,

*Louis A. Casadia, Esq.*
***@***.***
