### ISSUE TITLE
Adaptive Mesh for Delta Printers

### ISSUE THREAD

**Issue by jpbnto** [kyleisah/Klipper-Adaptive-Meshing-Purging#145]
**Describe the issue*
I think Delta printers is not yet supported

**What slicer are you using?**
Orcaslicer

**Troubleshooting**
I tried adjusting max mesh radius, same result

**Screenshots**
![image](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/assets/91659388/c08f64d3-2eb3-4cf7-957a-06e72835873c)

**Klipper log file:**
[klippy.log](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/files/12235181/klippy.log)

**Sliced Gcode**
[Cylinder left.gcode.txt](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/files/12235210/Cylinder.left.gcode.txt)

**Additional context**
Hope Delta Printes will be supoorted

**Comment by kyleisah** [comment]
KAMP has no delta support. I had something that theoretically worked on delta printers, but I don't have a delta so I can't troubleshoot or test anything.

**Comment by kyleisah** [comment]
@jpbnto are you on discord by any chance? I have something you can try.

**Comment by jpbnto** [comment]
Yes i am. 

Look me up jpbnto

**Comment by pradeep1080** [comment]
Hey @kyleisah I also want to try adaptive mesh in delta printers. Can I get any help?
