### ISSUE TITLE
BED_MESH_PROFILE LOAD=default 

### ISSUE THREAD

**Issue by choice3d** [kyleisah/Klipper-Adaptive-Meshing-Purging#146]
Sorry not an issue, wasn't sure where else to ask.

With Klipper no longer loading the default mesh on start up. Does this effect KAMP? Should I add BED_MESH_PROFILE LOAD=default to my start gcode/macro, or does KAMP load it automatically once the mesh is done?

Cheers

**Comment by choice3d** [comment]
Sorry, I may of miss read an update so this probably isn't a thing at all

**Comment by AudreyAP** [comment]
Klipper automatically loads the mesh once it finishes probing.

**Comment by kyleisah** [comment]
Audrey is correct. When KAMP generates a bed mesh, that same mesh will be used. No need to load.
