### ISSUE TITLE
Update for deprecated relative_reference_index parameter

### ISSUE THREAD

**Issue by davisgoodman** [kyleisah/Klipper-Adaptive-Meshing-Purging#148]
As the new klipper version is deprecating the relative_referene_index parameter, everytime I run an adaptive bed mesh I get the notification of the deprecated parameter..

Still works but I believe the current macro doesn't take care of the new zero_reference_position parameter

Is their an update that will take care of using the new zero_reference_position instead of the deprecated parameter or is the current code able to adapt without any modifications.

I've updated in the printer.cfg the [bed_mesh] section with the new parameter but I suppose this would need to be set for each bed mesh

I'm using SuperSlicer

**Comment by AudreyAP** [comment]
Remove relative_reference_index and add zero_reference_position to your printer.cfg.

KAMP has nothing to do with it, and nothing needs to be done per bed mesh. That's the point of the new setting :)

**Comment by davisgoodman** [comment]
Great, 

 

Thanks for the reply
