### ISSUE TITLE
After adding adaptive mesh and purge it alwasys does both twice

### ISSUE THREAD

**Issue by Wes910** [kyleisah/Klipper-Adaptive-Meshing-Purging#149]
**Describe the issue**
I added adaptive mesh and purge, When I start a print it wants to do them twice before the prints starts

**What slicer are you using?**
Superslicer

**Troubleshooting**
looked at printer cnfg and slicer settings

**Screenshots**

**Klipper log file:**
Please add klipper log file here...
[klippy.log](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/files/12269761/klippy.log)

**Sliced Gcode**
Please add sliced gcode file you are using here...
[Calibration cube.txt](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/files/12269741/Calibration.cube.txt)

**Additional context**
Thanks for the help

**Comment by kyleisah** [comment]
![image](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/assets/40312912/981199ba-1bdc-48dc-b965-54516aa18ac1)

Looks like for some reason, PRINT_START is being called twice by your slicer. Once as starting gcode, and again by filament gcode.

**Comment by Wes910** [comment]
Im not sure why superslicer is doing this?

![image](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/assets/137915067/5961f54e-1aea-40cc-bb9d-5178af7c45ed)

**Comment by Wes910** [comment]
I got it sorted, evidently super slicer has a custom g code sections for the filament and printer. I had the code in both, I must not realised I was in one and not the other
