### ISSUE TITLE
Error evaluating 'gcode_macro BED_MESH_CALIBRATE:gcode': TypeError: bad operand type for abs(): 'Undefined'

### ISSUE THREAD

**Issue by deonkretch** [kyleisah/Klipper-Adaptive-Meshing-Purging#155]
**Describe the issue**
File sliced with Orca Slicer - I get this error:

**7:24 PM
Error evaluating 'gcode_macro BED_MESH_CALIBRATE:gcode': TypeError: bad operand type for abs(): 'Undefined'**

**What slicer are you using?**
Orca Slicer 1.6.4

**Troubleshooting**
Restarted printer multiple times.

**Klipper log file:**
[klippy (3).log](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/files/12330032/klippy.3.log)

**Sliced Gcode**
[benchy.gcode.zip](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/files/12330036/benchy.gcode.zip)

**Additional context**
No additional context.

**Comment by kyleisah** [comment]
Did you delete the `variable_probe_dock_enable` line rather than set it to false?

**Comment by kyleisah** [comment]
no replies

**Comment by kyleisah** [comment]
@mairisskuja i think that having it the way it is now makes sense. Nowhere in the documentation does it tell you to comment it out or delete it.
