### ISSUE TITLE
Move nozzle out after purge

### ISSUE THREAD

**Issue by mrodyhin** [kyleisah/Klipper-Adaptive-Meshing-Purging#156]
In the current LINE_PURGE macro the last command is doing Z hop, and releases control to the next gcode.
The issue is that it's very likely, that the first move command generated by slicer, is move Z to the first layer height.
That results in a wired behaviour, that nozzle goes up, than back down, and than starts moving by XY axis thought the purge line.

Here is what i got: 
<img width="1036" alt="image" src="https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/assets/11924548/e1f20b3a-bfc3-44a8-a65c-c55c74d6d0b4">

I tried to fix it by adding additional move in my print start macro after the purge, but i doesn't always work, since the purge macro can place the line on X or Y axis.

The proposal is to add additional XY move towards the modal, to move nozzle out of the purge line.

**Comment by kyleisah** [comment]
Hey there! Just letting you know this has already been fixed and will eventually be pushed in the next update.

**Comment by mrodyhin** [comment]
That's a great news, thank you very much.

**Comment by kyleisah** [comment]
This is now in the main release. :)
