### ISSUE TITLE
Cant start work after probe - keep asking for Must home axis first

### ISSUE THREAD

**Issue by Assafm42** [kyleisah/Klipper-Adaptive-Meshing-Purging#157]
**Describe the issue**
After setting all the thing by deigning in google and youtube I keep getting the Must home axis first: 0.000 0.000 5.000 [0.000]

After sending the file to the printer the printer start heating up and the probe process finish around the print aerie.
Whan the probe process finished I all the time get the Must home axis massage.

Try to Calibrate my mash and my probe offset.

Printer: Ender 3 V2
BL Touch probe
Klipper + Mainsail
Max bed size in klipper - 225/225
Using  Cura 5.4 slicer 

Massage from console
9:55 PM
Must home axis first: 0.000 0.000 5.000 [0.000]
9:55 PM
Must home axis first: 0.000 0.000 5.000 [0.000]
9:55 PM
Must home axis first: 0.000 0.000 5.000 [0.000]
9:55 PM
8 | (184.5, 187.2) | (138.5, 181.2)
9:55 PM
7 | (149.7, 187.2) | (103.7, 181.2)
9:55 PM
6 | (115.0, 187.2) | (69.0, 181.2)
9:55 PM
5 | (115.0, 116.0) | (69.0, 110.0)
9:55 PM
4 | (149.7, 116.0) | (103.7, 110.0)
9:55 PM
3 | (184.5, 116.0) | (138.5, 110.0)
9:55 PM
2 | (184.5, 44.8) | (138.5, 38.8)
9:55 PM
1 | (149.7, 44.8) | (103.7, 38.8)
9:55 PM
0 | (115.0, 44.8) | (69.0, 38.8)
9:55 PM
bed_mesh: generated points
Index | Tool Adjusted | Probe
9:55 PM
Generating new points...
9:55 PM
KAMP adjustments successful. Happy KAMPing!
9:55 PM
Adapted mesh bounds: (68.972, 38.804), (138.499, 181.194).
9:55 PM
Fuzz amount is 0, mesh points not fuzzed.
9:55 PM
Mesh margin is 0, margin not increased.
9:55 PM
Default mesh bounds: (9.0, 9.0), (182.0, 219.0).
9:55 PM
Adapted probe count: 3,3.
9:55 PM
Default probe count: 3,3.
9:55 PM
Algorithm: lagrange.
9:51 PM
File selected
9:51 PM
File opened:CE3E3V2_slot_cover_143mm_original.gcode Size:1075345
9:51 PM
SDCARD_PRINT_FILE FILENAME="CE3E3V2_slot_cover_143mm_original.gcode" 

My Printer.cfg file

# This file contains pin mappings for the stock 2020 Creality Ender 3
# V2. To use this config, during "make menuconfig" select the
# STM32F103 with a "28KiB bootloader" and serial (on USART1 PA10/PA9)
# communication.

# If you prefer a direct serial connection, in "make menuconfig"
# select "Enable extra low-level configuration options" and select
# serial (on USART3 PB11/PB10), which is broken out on the 10 pin IDC
# cable used for the LCD module as follows:
# 3: Tx, 4: Rx, 9: GND, 10: VCC

# Flash this firmware by copying "out/klipper.bin" to a SD card and
# turning on the printer with the card inserted. The firmware29
# filename must end in ".bin" and must not match the last filename
# that was flashed.
# See docs/Config_Reference.md for a description of parameters.
##you can  level the bed. First, home with G28 and type SCREWS_TILT_CALCULATE to adjust the bed. You can type SCREWS_TILT_CALCULATE multiple times until it’s close.
##To level the bed, you can run BED_MESH_CALIBRATE. After calibration, make sure to hit SAVE_CONFIG
#Tuning PIDs
#It’s really simple to tune your extruder and bed PIDs. 
#Just run PID_CALIBRATE HEATER=extruder TARGET=200 
#and PID_CALIBRATE HEATER=heater_bed TARGET=60.
# Don’t forget to SAVE_CONFIG after each run!
# Macros 
[include Line_Purge.cfg]
[include macros.cfg]
[include ./KAMP/Smart_Park.cfg]
[include Adaptive_Meshing.cfg]
[include KAMP_Settings.cfg]
[firmware_retraction]
retract_length: 3
#   The length of filament (in mm) to retract when G10 is activated,
#   and to unretract when G11 is activated (but see
#   unretract_extra_length below). The default is 0 mm.
retract_speed: 40
#   The speed of retraction, in mm/s. The default is 20 mm/s.
unretract_extra_length: 0
#   The length (in mm) of *additional* filament to add when
#   unretracting.
unretract_speed: 30
#   The speed of unretraction, in mm/s. The default is 10 mm/s.
#[include fluidd.cfg]
[display_status]
[virtual_sdcard]
path: ~/printer_data/gcodes
[exclude_object]
[stepper_x]
step_pin: PC2
dir_pin: PB9
enable_pin: !PC3
microsteps: 16
rotation_distance: 39.81
endstop_pin: ^PA5
position_endstop: 0
position_min: 0
position_max: 250 #238
homing_speed: 100
[stepper_y]
step_pin: PB8
dir_pin: PB7
enable_pin: !PC3
microsteps: 16
rotation_distance: 39.52 #40
endstop_pin: ^PA6
position_endstop: 0
position_min: 0
position_max: 225
homing_speed: 100
[stepper_z]
step_pin: PB6
dir_pin: !PB5
enable_pin: !PC3
microsteps: 16
rotation_distance: 7.94
endstop_pin: probe:z_virtual_endstop
#position_endstop: 0.0
position_max: 225
position_min: -6
[bltouch]
#https://www.youtube.com/watch?v=4Y35XzPKjUs&t=1s
sensor_pin: ^PB1
control_pin: PB0
x_offset: -46
y_offset: -6
#z_offset: 4
speed: 20
samples: 3
#pin_up_touch_mode_reports_triggered: False
[safe_z_home]
speed: 200
home_xy_position: 161,123 #117.5,117.5
z_hop: 10
z_hop_speed: 100
[bed_mesh]
speed: 200
horizontal_move_z: 5
mesh_min: 9,9
mesh_max: 182,219
probe_count: 3,3
#mesh_pps: 2,2 #new
algorithm: bicubic
fade_start: 1
fade_end: 10
fade_target: 0
##you can  level the bed. First, home with G28 and type SCREWS_TILT_CALCULATE to adjust the bed. You can type SCREWS_TILT_CALCULATE multiple times until it’s close.
##To level the bed, you can run BED_MESH_CALIBRATE. After calibration, make sure to hit SAVE_CONFIG
[screws_tilt_adjust]
screw1: 75,35
screw1_name: front left screw
screw2: 235,35
screw2_name: front right screw
screw3:235,200
screw3_name: rear right screw
screw4: 75,200
screw4_name: rear left screw
horizontal_move_z: 10
speed: 100
screw_thread: CW-M4
[verify_heater extruder]
check_gain_time: 240
max_error: 240
[extruder]
max_extrude_only_distance: 80.0
step_pin: PB4
dir_pin: PB3
enable_pin: !PC3
microsteps: 16
rotation_distance: 33.165#32.513
nozzle_diameter: 0.600
filament_diameter: 1.750
heater_pin: PA1
sensor_type: EPCOS 100K B57560G104F
sensor_pin: PC5
#control: pid
# tuned for stock hardware with 200 degree Celsius target
#pid_Kp: 21.527
#pid_Ki: 1.063
#pid_Kd: 108.982
min_temp: 0
max_temp: 300
min_extrude_temp: 0
max_extrude_only_distance: 750
max_extrude_cross_section: 5
[heater_bed]
heater_pin: PA2
sensor_type: EPCOS 100K B57560G104F
sensor_pin: PC4
#control: pid
# tuned for stock hardware with 50 degree Celsius target
#pid_Kp: 54.027
#pid_Ki: 0.770
#pid_Kd: 948.182
min_temp: 0
max_temp: 130
[fan]
pin: PA0
[mcu]
serial: /dev/serial/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.1:1.0-port0
#serial: /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
restart_method: command
[mcu rpi]
serial: /tmp/klipper_host_mcu
[adxl345]
cs_pin: rpi:None
[resonance_tester]
accel_chip: adxl345
probe_points:
    100, 100, 20  # an example
[printer]
kinematics: cartesian
max_velocity:200
max_accel: 3000
max_accel_to_decel: 3000
max_z_velocity: 5
max_z_accel: 200
square_corner_velocity: 5
[pause_resume]
#*# <---------------------- SAVE_CONFIG ---------------------->
#*# DO NOT EDIT THIS BLOCK OR BELOW. The contents are auto-generated.
#*#
#*# [extruder]
#*# control = pid
#*# pid_kp = 24.339
#*# pid_ki = 1.193
#*# pid_kd = 124.128
#*#
#*# [heater_bed]
#*# control = pid
#*# pid_kp = 76.011
#*# pid_ki = 1.898
#*# pid_kd = 761.064
#*#
#*# [bltouch]
#*# z_offset = 0.910

**Comment by kyleisah** [comment]
This is not a KAMP issue, this is something going on in your config. I'm guessing you need to take a look in your print_start macro and fix the issue.
