### ISSUE TITLE
How can I change the adaptive purge settings?

### ISSUE THREAD

**Issue by SXRguyinMA** [kyleisah/Klipper-Adaptive-Meshing-Purging#159]
How can I change the adaptive purge settings?

The KAMP config file is read-only and I can't see how to make it editable so I can change the settings

**Comment by kyleisah** [comment]
In the same directory as your printer.cfg file, there should be a KAMP_Settings.cfg file, that is where you're supposed to change the settings for all of KAMP.

Do you have that file there?

![image](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/assets/40312912/0b255f69-10f9-40ef-9b4d-753553562372)

**Comment by SXRguyinMA** [comment]
No but I have Line_Purge.cfg however changing the settings in there doesn't change anything as far as the output is concerned

![settings](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/assets/13491698/f5d9e1a4-359c-414e-ab2e-e25009cc399e)

**Comment by kyleisah** [comment]
I think you should go back through the instructions. You don't need to move anything out of the KAMP folder. You just need the settings file, and make your changes in there.

**Comment by SXRguyinMA** [comment]
> I think you should go back through the instructions. You don't need to move anything out of the KAMP folder. You just need the settings file, and make your changes in there.

Alright I'll look into that, thanks. I don't recall moving anything when I did the initial install but I'll make sure I don't.
