### ISSUE TITLE
Existing command 'BED_MESH_CALIBRATE' not found in gcode_macro rename

### ISSUE THREAD

**Issue by tpattl** [kyleisah/Klipper-Adaptive-Meshing-Purging#161]
The titled error appears after following Requirements and Installation steps.

I am using OrcaSlicer, though have not had the chance to test a print.

Log file attached

**Comment by tpattl** [comment]
> The titled error appears after following Requirements and Installation steps.
> 
> I am using OrcaSlicer, though have not had the chance to test a print.
> 
> Log file attached

[klippy (2).log](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/files/12389123/klippy.2.log)

Or NOW it's attached.  Whoops!

**Comment by kyleisah** [comment]
You don't have a [bed_mesh] section defined in your config.
