### ISSUE TITLE
Updating to new version.

### ISSUE THREAD

**Issue by ak1ca1** [kyleisah/Klipper-Adaptive-Meshing-Purging#162]
Hello!, I've been using older KAMP version and wanted to upgrade to newer one. Im still new and learning klipper and other stuff.

I did installation and everything. Now my question is do I need to add KAMP_Settings in cura start g-code? 
In older version I did add BED_MESH_CALIBRATE and LINE_PURGE in cura start g-code. Now I need to remove both right ?
sorry for stupid question's.

**Comment by kyleisah** [comment]
It would honestly be easier to just remove all of the old stuff and redo the setup.
