### ISSUE TITLE
Error evaluating 'gcode_macro BED_MESH_CALIBRATE:gcode': TypeError: object of type 'int' has no len()

### ISSUE THREAD

**Issue by scheini79** [kyleisah/Klipper-Adaptive-Meshing-Purging#163]
**Describe the issue**
When starting a print i get this Error Message

**What slicer are you using?**
Superslicer 2.5.59, Orcaslicer 1.6.6

**Troubleshooting**
Already changed probe_points to round_probe_points (because i am using a Delta) to get rid of this error message: Error evaluating 'gcode_macro BED_MESH_CALIBRATE:gcode': UndefinedError: 'probe_count' is undefined 

**Sliced Gcode**
[Overhang_test_45-85_PLA_24m27s.zip](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/files/12431242/Overhang_test_45-85_PLA_24m27s.zip)
[Overhang_test_45-85.zip](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/files/12431243/Overhang_test_45-85.zip)

Please add sliced gcode file you are using here...

**Additional context**
[klippy.log](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/files/12431216/klippy.log)

**Comment by kyleisah** [comment]
Delta is not currently supported. I don't own a delta and cannot develop for it.
