### ISSUE TITLE
More Points for Mesh?

### ISSUE THREAD

**Issue by dmaxwellNEU** [kyleisah/Klipper-Adaptive-Meshing-Purging#164]
Maybe this isn't the best spot to put this, as it's not really an issue as much as it may be user error or a lacking feature. I'm wondering if there is a setting in adaptive meshing to be able to measure more points when the mesh size becomes larger. When I probe the whole bed, it's still only using a 3x3 which is not very accurate. Is there a setting that increases the number of probe points? Or is this feature just not working for me, and it's already there?

Thanks!

**Comment by kyleisah** [comment]
In your printer.cfg [bed_mesh] settings you can increase the probe points. 

3x3 will always be the smallest it can adapt to, but I usually have the config set to 7,7 so a full bed will be a bigger mesh.

**Comment by dmaxwellNEU** [comment]
Thanks so much I'll give that a try. I didn't realize that it wasn't set in my config file. I suppose that means it just defaults to 3x3. Thanks!
