### ISSUE TITLE
Kamp is not meshing

### ISSUE THREAD

**Issue by Awesome4all** [kyleisah/Klipper-Adaptive-Meshing-Purging#165]
I have been trying at this for the past 2 hours. when I start my print Kamp loads but does not create the mesh around my part it just does the default mes. Yes I have Tried the M117.

**What slicer are you using?**
Prusaslicer

**Troubleshooting**
I have tried changing mesh size in printer.cfg. 

**Screenshots**
![image](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/assets/78572109/0d1656d2-d970-4a5d-820a-bd211e796692)
![image](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/assets/78572109/00a85110-4f21-4440-817f-c9f91cc9ae4d)

**log and gcode**
[kamp issue.zip](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/files/12444641/kamp.issue.zip)

**Comment by kyleisah** [comment]
Are you putting M117 before print start *in your slicer*? The M117 trick doesn't work from inside the print start macro, it has to be in the slicer's gcode before PRINT_START is called

**Comment by kyleisah** [comment]
Like this:
<img width="276" alt="image" src="https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/assets/40312912/f4af6abb-58de-4748-abab-80bf7c792245">

**Comment by Awesome4all** [comment]
oh okay let me try that

**Comment by Awesome4all** [comment]
Yes that worked tysm

**Comment by hapsti** [comment]
what is the M117 trick?

**Comment by kyleisah** [comment]
> what is the M117 trick?

Have a look in the troubleshooting section in the readme. 

It's a trick to force moonraker to define objects in the correct spot in your gcode file.

**Comment by Awesome4all** [comment]
> what is the M117 trick?

Yes it was
