### ISSUE TITLE
How do you actually use KAMP? Show your PRINT_START

### ISSUE THREAD

**Issue by Stooovie** [kyleisah/Klipper-Adaptive-Meshing-Purging#170]
I'm at bit of a loss about how to actually USE the KAMP stuff. I can call the macros, no issue there, but I don't know where in the PRINT_START macro to actually put the KAMP macros. 

Here's my START_PRINT:
```
[gcode_macro START_PRINT]
gcode:
	G92 E0 ; Reset Extruder
	{% set BED_TEMP = params.BED_TEMP|default(60)|float %}
	{% set EXTRUDER_TEMP = params.EXTRUDER_TEMP|default(190)|float %}
	M140 S{BED_TEMP} ;Start heating bed
	CG28 ; Home all axes
  M104 S{EXTRUDER_TEMP} ;Start heating extruder
	M190 S{BED_TEMP} ;Wait for bed to reach temp before proceeding
	#BED_MESH_CALIBRATE ; Auto bed leveling
	G1 Z2.0 F3000 ; Move Z Axis up little to prevent scratching of Heat Bed
	G1 X0.1 Y30 Z0.3 F5000.0 ; Move to start position
	M109 S{EXTRUDER_TEMP} ;Wait for extruder to reach temp before proceeding
  clean_nozzle
	G1 X0.1 Y200.0 Z0.3 F1500.0 E15 ; Draw the first line
	G1 X0.4 Y200.0 Z0.3 F5000.0 ; Move to side a little
	G1 X0.4 Y10 Z0.3 F1500.0 E30 ; Draw the second line
	G92 E0 ; Reset Extruder
	G1 Z2.0 F3000 ; Move Z Axis up little to prevent scratching of Heat Bed
	G1 X5 Y20 Z0.3 F5000.0 ; Move over to prevent blob squish
```
There's a "clean_nozzle" submacro that scrapes the nozzle on a wire brush at bottom left of the plate. I have no idea if this is the ideal place, and where would I put "line_purge" in here. Do I just replace the G1 lines after "clean_nozzle"? What about the G92 and last two lines? Replace with Smart_park?

I want to have this set up correctly so KAMP is actually beneficial.

Thanks!

**Comment by kyleisah** [comment]
Remove everything after clean nozzle, and just add LINE_PURGE. SMART_PARK is used for parking the printhead near the print area to heat up, but since you have a place to scrub you don't need to use it.
