### ISSUE TITLE
[Feature Request] Reverse Direction for Line Purge

### ISSUE THREAD

**Issue by dstulken** [kyleisah/Klipper-Adaptive-Meshing-Purging#172]
**Describe the issue**
This is a feature request.  The default line purge moves the nozzle from left to right while purging.  This means that the pre-purge ooze blobs, which may be of large, partially solidified, or irregular shapes, end up being deposited on the left side of the purge line and then anchored to the bed by the purge. 

When the purge line is in process, as the nozzle moves to the right, my inductive probe sometimes collides with these blobs.  It usually just scrapes by, but I believe this would be a larger concern for BLTouch users as the probe tip is more mechanically delicate.

If the KAMP purge line could be configurable to move from _right-to-left_, instead of left-to-right, then any debris would be on the opposite side of the nozzle, and would not have any chance of interfering with the bed probe.  

(Thanks in advance - really appreciate what KAMP has brought to this hobby.)

**Comment by kyleisah** [comment]
You can adjust the purge to purge at a different height, different flow, and different amount. Tune it for your machine.
