### ISSUE TITLE
Uninstall KAMP or at least change the retraction

### ISSUE THREAD

**Issue by Aaron3160** [kyleisah/Klipper-Adaptive-Meshing-Purging#177]
**Describe the issue**
I want to change the retraction of the purge line and not use firmware retraction.
I want to use slicer retraction for wipe etc.
Is there a way I can change the default retraction of .5 mm or uninstall KAMP and use normal configs i can edit?

**Comment by kyleisah** [comment]
You can use both... just turn off firmware retraction in your slicer.
