### ISSUE TITLE
Probe triggered prior to movement with Klicky

### ISSUE THREAD

**Issue by ogland** [kyleisah/Klipper-Adaptive-Meshing-Purging#18]
As in the title. 

variable_probe_dock_enable: True

Even tested setting these to lowercase
variable_attach_macro: 'attach_probe'
variable_detach_macro: 'dock_probe'

**Comment by kyleisah** [comment]
I'm a little confused. Can you tell me exactly what is happening? Is the klicky probe not getting picked up?

**Comment by ogland** [comment]
It's just as if the attach_probe macro isn't triggering at all. If I add the attach_probe macro before BED_MESH_CALIBRATE then it probes the bed like normal.

**Comment by ogland** [comment]
I didn't link the cfg file.. I'm sorry.
