### ISSUE TITLE
UndefinedError: 'dict object' has no attribute 'polygon'

### ISSUE THREAD

**Issue by lsmelvin** [kyleisah/Klipper-Adaptive-Meshing-Purging#182]
**Describe the issue**
A clear and concise description of what the bug is...

Error evaluating 'gcode_macro BED_MESH_CALIBRATE:gcode': jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'polygon'

**What slicer are you using?**
Prusaslicer, Superslicer, Cura, Orcaslicer...

superslicer

**Troubleshooting**
What troubleshooting steps have you tried?

looking online and triple checking work

**Screenshots**

![kamp error](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/assets/145748468/7b1d39e3-95a7-4e63-bc7b-ff980974afb0)

**Klipper log file:**
Please add klipper log file here...

[klippy.log](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/files/12697702/klippy.log)

**Sliced Gcode**
Please add sliced gcode file you are using here...

**Additional context**

already added exclude_object in printer.cfg and checked label objects in superslicer followed setup guides and videos to a T so im unsure what im doing wrong.

![kamp error 2](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/assets/145748468/acbaa038-a7a5-4ecf-92fb-5ea184f2fef2)

![kamp error 3](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/assets/145748468/122eefef-f1dd-411e-aa76-1210a125bc4e)

**Comment by julianschill** [comment]
Please add a sliced gcode file. That helps to find the problem.

**Comment by Theo9909** [comment]
Recently had to rebuild my system. Now this error pops up everytime I try using adaptive meshing. I had no issues until the redo. Used the same macros, and printer.cfg files. 

 How can I include the preprocessed gcode?

**Comment by Theo9909** [comment]
[gcodes-202380-181521.zip](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/files/12709774/gcodes-202380-181521.zip)
Gcode file from klipper setup attached.

**Comment by julianschill** [comment]
Something went wrong with the preprocessing. Please also add the moonraker.log

**Comment by Theo9909** [comment]
[moonraker.zip](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/files/12709908/moonraker.zip)

**Comment by julianschill** [comment]
You are using "machinekit" as gcode flavor in Prusaslicer. This results in wrong G1 commands with Axx instead of Exx, which causes the problem.
Change the gcode flavor to "Klipper" (or "Marlin legacy" for older Prusaslicer versions) in the printer settings and it should work.

**Comment by Theo9909** [comment]
That's interesting, as I haven't changed that setting in prusa slicer since before I had the Ethernet issues. I'll get that changed and what it work like it always did.

Thank you, I will update shortly.

**Comment by Theo9909** [comment]
That did it. Not sure how that changed, but two days of trying everything and never looking at that setting once against n proves that I need to look at the simple things first. Thank you for your help! Hopefully the OP is able to gleam some info off of this. Take care.

**Comment by kyleisah** [comment]
> That did it. Not sure how that changed, but two days of trying everything and never looking at that setting once against n proves that I need to look at the simple things first. Thank you for your help! Hopefully the OP is able to gleam some info off of this. Take care. 

I would have never thought to check gcode flavor. I will be sure to make a note of this or add something in the troubleshooting section for it.
