### ISSUE TITLE
Skirt going through Voron purge.

### ISSUE THREAD

**Issue by DeW-Z** [kyleisah/Klipper-Adaptive-Meshing-Purging#184]
**Describe the issue**
Setup KAMP and it worked flawlessly for a few weeks, but now I am getting seemingly random occurrences where the skirt goes through the Voron purge, causing the print to fail sometimes.

**What slicer are you using?**
Prusaslicer

**Troubleshooting**
Verify all stock settings to be in place.

**Screenshots**
[Photo 1.](https://imgur.com/a/7Bldtjp)

**Klipper log file:**
[Link to Klippy Log](https://drive.google.com/file/d/1NXZwI7wdQ4t18m9ch_O3nDYWpnNgF7lc/view?usp=sharing)

**Sliced Gcode**
[Link to File
](https://drive.google.com/file/d/1gtFQOqGhYAkZrUExLeq7MnbXZKoPXswN/view?usp=sharing)

**Additional context**
Sometimes is puts the skirt through the purge, sometimes not. No changes to slicer profile.

**Comment by julianschill** [comment]
Exclude_object doesn’t detect the skirt. So Kamp also doesn’t know about it. To fix this just increase the variable_purge_margin until it fits.
