### ISSUE TITLE
Feature Request: change smart_park postition behind the print

### ISSUE THREAD

**Issue by fabiandj64** [kyleisah/Klipper-Adaptive-Meshing-Purging#187]
I use the smart park feature to park my printhead near the print to insert something into the print and then continue (e.g. magnets)

because smart park puts the toolhead in front of the actual print, it is harder for me to put in the magnets because i have to maneuver around the toolhead. if the toolhead moves behind the print the view is not obstructed and i could put in the magnets very easy

**Comment by kyleisah** [comment]
I think for your use-case, you'd be better off using some kind of smarter PAUSE macro. Smart_Park is really only useful for being near the print area to heat up the nozzle to final temperature. This is an interesting idea though!
