### ISSUE TITLE
Move out of Z range while smart park

### ISSUE THREAD

**Issue by mrodyhin** [kyleisah/Klipper-Adaptive-Meshing-Purging#189]
**Describe the issue**
I'm using adaptive meshing + smart part with the really small `variable_smart_park_height` to prevent nozzle leak while heating:
```variable_smart_park_height: 0.1``` 

The issue appears when smart park chooses exact position of the edge mesh point to park the head, and that point probes negative to zero.

Here is the log of the issue:

```
10:34:25 Move out of range: 75.500 103.000 -0.030 [-0.500]
10:34:25 Move out of range: 75.500 103.000 -0.030 [-0.500]
10:34:25 Move out of range: 75.500 103.000 -0.030 [-0.500]
10:34:25 Smart Park location: 75.5,103.
```
We can see that, smart park location is selected to `75.5,103.` which is exactly the edge mesh point. 
let's look into the mesh:
<img width="761" alt="Screenshot 2023-10-02 034746" src="https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/assets/11924548/2939005d-b9e5-4506-80ac-d988f6888826">
As we can see, that point is probed as Z: `-0.13`, while my `variable_smart_park_height` is set to `0.1`, that gives us `-0.03` out of range that is mentioned in the error message.

**What slicer are you using?**
Doesn't matter

**Troubleshooting**
I tried to increase adaptive mesh margin, but no mater what i set, smart park chooses edge point to park.  

**Additional context**
I believe the issue could be fixed by moving park point a little bit into the mesh instead of parking on the edge.

**Comment by kyleisah** [comment]
I think you should just increase the park height. Parking with Z that low during heatup can damage bed surfaces. The default height is 10, which is reasonable. You might also want to investigate what is causing your mesh to be generated below 0. 

You can benefit from something like `zero_reference_position` in your `[bed_mesh]` config. [Here is where you can find that.](https://www.klipper3d.org/Bed_Mesh.html#configuring-the-zero-reference-position)
