### ISSUE TITLE
Parking is not honoring the defined `purge_margin`

### ISSUE THREAD

**Issue by Johan3F** [kyleisah/Klipper-Adaptive-Meshing-Purging#191]
When enabling the smart parking, the variable `purge_margin` is supposed to be used to allow for a certain gap between the print and the nozzle.

**Additional context**
I've discovered this because my nozzle is quite oozes quite a bit, so I was ending up with a blob of plastic in one of my print's corner

**Comment by kyleisah** [comment]
Fixed with PR #216
