### ISSUE TITLE
First Layer Height Adjustment Issue with Auto Z

### ISSUE THREAD

**Issue by leitenky** [kyleisah/Klipper-Adaptive-Meshing-Purging#194]
**Describe the issue**
I have a Voron 2.4r2 with Klicky, and Auto Z calibrate. I can adjust the Switch Offset for Auto Z and first layer height seems to adjust properly. When I enable the adaptive mesh I cannot get the Auto Z "switch offset value" to impact the first layer height anymore.

**What slicer are you using?**
Superslicer

**Troubleshooting**
Enabling and Disabling Mesh to verify Auto Z "switch offset value" is functioning
zero_reference_position set with same value in printer.cfg and KAMP_settings

**Klipper log file:**
[klippy.log](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/files/12862823/klippy.log)

**Additional context**
I have these values in the Printer.cfg that are "Auto Generated" could they be causing an issue?
#*# [probe]
#*# z_offset = 6.720
#*#
#*# [stepper_z]
#*# position_endstop = 1.089

**Comment by kyleisah** [comment]
KAMP doesn’t do anything to the Z height for a mesh, it only adjusts the bounds of the mesh. Your issue lies elsewhere I think. You could reach out to the creator of auto Z and see if they know anything?
