### ISSUE TITLE
Purge Line always start at (0,0)

### ISSUE THREAD

**Issue by ylqiu2000** [kyleisah/Klipper-Adaptive-Meshing-Purging#195]
**Describe the issue**
I have Voron 0 without any probes, the Purge Line always starts (0,0) regardless of Line_Purge or Voron_Purge. 

**What slicer are you using?**
Prusaslicer

**Troubleshooting**
KAMP_Setting is responding correctly after changing the parameters inside the file. I have tried with different objects and locations of the build plate. Exclude object is working correctly as it shows up during print. 

**Screenshots**
![image](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/assets/136993632/4c1c82d8-8975-4da0-8420-081f774a7723)
![image](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/assets/136993632/93c100ee-a062-40df-8a1d-9f2e6e8167fe)
![image](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/assets/136993632/a31de752-ee5c-42f2-a5d8-e0aa87ad1b2d)

**Klipper log file:**
[klippy.log](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/files/12885675/klippy.log)

**Comment by kyleisah** [comment]
In your slicer, try adding M117 before print_start. It's a common issue with the preprocessor unfortunately.

**Comment by ylqiu2000** [comment]
That is such a niche error, thank you very much for resolving this!
