### ISSUE TITLE
error when trying to do bed mesh 

### ISSUE THREAD

**Issue by VHumpal** [kyleisah/Klipper-Adaptive-Meshing-Purging#196]
**Describe the issue**
A clear and concise description of what the bug is...
i start my print it heats up homes and then i get this error when it trys to doing the probing 

Error evaluating 'gcode_macro BED_MESH_CALIBRATE:gcode': jinja2.exceptions.UndefinedError: 'extras.gcode_macro.GetStatusWrapper object' has no attribute 'gcode_macro _KAMP_Settings'

**What slicer are you using?**
Prusaslicer, Superslicer, Cura, Orcaslicer...
im using cure 5.4 and i have tried orca slicer

**Troubleshooting**
What troubleshooting steps have you tried?
i have tried diffrent slicers chnaging settings 
**Screenshots**

<img width="879" alt="Screenshot 2023-10-13 at 10 31 44 AM" src="https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/assets/147843235/34bd8281-0021-4446-9f7a-22b40182d86f">

**Klipper log file:**
Please add klipper log file here...

[klippy.log.zip](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/files/12895242/klippy.log.zip)

**Sliced Gcode**
Please add sliced gcode file you are using here...

[CE3S1PRO_3dbenchy.gcode.zip](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/files/12895231/CE3S1PRO_3dbenchy.gcode.zip)

**Additional context**

**Comment by kyleisah** [comment]
At a glance I think you forgot to [include] KAMP_Settings.cfg

**Comment by VHumpal** [comment]
where do i need to include it?

**Comment by kyleisah** [comment]
In printer.cfg

**Comment by VHumpal** [comment]
i got it working thank you

**Comment by kyleisah** [comment]
No worries!
