### ISSUE TITLE
Adaptive mesh ignoring probe_count setting

### ISSUE THREAD

**Issue by dJOS1475** [kyleisah/Klipper-Adaptive-Meshing-Purging#20]
Howdy, Adaptive mesh is ignoring my probe_count: 5,5 setting and only probing a 3x3 matrix. This setting was being properly implemented before adding Adaptive mesh to the mix.

![Screenshot 2023-01-12 at 9 26 07 am](https://user-images.githubusercontent.com/39177227/211931796-7e76771e-ad16-476e-8163-6f904426bd09.jpg)

![Screenshot 2023-01-12 at 9 25 47 am](https://user-images.githubusercontent.com/39177227/211931821-77a9bc95-8a60-47f9-80a9-5892991e5179.jpg)

PS, love your work team!

Cheers Derek

**Comment by dJOS1475** [comment]
Hmmm, looks like it works fine for larger prints - is going to a 3x3 for a smaller print part of the "adaptive" nature of this system?

**Comment by karlla1220** [comment]
Based on my reading of codes, it use probe_count only to define a step size between probing point. if given a step size is (30, 30) and print area is (60, 60) to (150, 150), then, the code would use 3 by 3 mesh. Thus, probe_count defines granularity of adaptive mesh. Seems reasonable.

**Comment by dJOS1475** [comment]
Based on fine more testing, lager prints will use the full 5x5 matrix and smaller prints won’t. Which is fine, it’s just not clear in the doco.
