### ISSUE TITLE
Getting error when start print

### ISSUE THREAD

**Issue by HasibTheNeWb** [kyleisah/Klipper-Adaptive-Meshing-Purging#204]
Getting 
SDCARD_RESET_FILE cannot be run from the sdcard
5:21 PM
SDCARD_RESET_FILE cannot be run from the sdcard
5:21 PM
Error evaluating 'gcode_macro BED_MESH_CALIBRATE:gcode': UndefinedError: 'instance object' has no attribute 'gcode_macro _KAMP_Settings'

What can I do??

**Comment by kyleisah** [comment]
Do you have `[include KAMP_Settings.cfg]` in your printer.cfg?

Also, a klipper log file really helps.

**Comment by kyleisah** [comment]
Any updates?
