### ISSUE TITLE
Is there a way to show the probe progress in the console?

### ISSUE THREAD

**Issue by thiagoabdo** [kyleisah/Klipper-Adaptive-Meshing-Purging#206]
Hi, I would like to to know if there is a setting or a way of displaying the progress while doing the initial probing?

I known that at the begging it says how many probe points it will make, but it always passes so fast and there is no way to known in which probe it is at the moment. 

With normal probing I could infer based in the size of the bed, but with adaptation I cannot use it as a metric. Knowing the progress would help with my anxiety.

If it displayed something like probing X/Y before probing a point, it would be super nice!

I am happy to help if I can :)

**Comment by kyleisah** [comment]
There’s nothing I can do about that unfortunately, that is just how klipper handles outputting probe measurements to the console. 

Something you can try though is using a console filter in Fluidd/Mainsail to filter out messages containing certain words so you can tailor the output a little more how you want it. 

Best of luck to you!
