### ISSUE TITLE
KAMP

### ISSUE THREAD

**Issue by mendeste** [kyleisah/Klipper-Adaptive-Meshing-Purging#207]
**Describe the issue**
Hi will KAMP work on SONIC PAD using Ender 5 S1

**What slicer are you using?**
Orcaslicer...

**Comment by kyleisah** [comment]
I can’t say for sure, because I do not have one. But as long as you have access to the config files and moonraker, I don’t see why not.

**Comment by mendeste** [comment]
Hi Kyleisah
I've already tried but can't get line or voron purge to work
Cheers

**Comment by mendeste** [comment]
Sorry
Just remembered to need to change the start and code in Orca

Regards
