### ISSUE TITLE
KAMP triggering MCU Panic

### ISSUE THREAD

**Issue by Eliminateur** [kyleisah/Klipper-Adaptive-Meshing-Purging#211]
**Describe the issue**
Running BED_MESH_CALIBRATE after several points crashes klipper with "**MCU 'mcu' shutdown: ADC out of range**"
On small real prints(that only probe the surface of the object) it doesn't happens, seems to dependant on how much time probing takes

Probe is BLtouch, XY cartesian printer.

**Troubleshooting**
Ran BED_MESH_CALIBRATE from the klipper console on a completely cold printer (no heaters running)

In the attached klippy log on line 6708 you can see the last received command before the crash:
07:46:11 PM Probing failed due to printer shutdown
07:46:11 PM Klipper state: Shutdown
07:46:09 PM probe at 273.000,62.831 is z=1.135625

Already updated all the software to the latest available
![image](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/assets/55205206/bd5818f0-9284-4a7c-ace0-b8e4df34d0ff)

[klippy.log](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/files/13210689/klippy.log)

**Comment by kyleisah** [comment]
ADC being out of range typically relates to a thermistor issue. Like a wire breakage, loose connection, dying thermistor etc. 

I uploaded your log file to an analyzer and got your temperature graph here:

![image](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/assets/40312912/562c06c6-0a1b-4cec-9a29-1389c19a2676)

So it looks like this isn’t a KAMP issue, but a machine issue.

**Comment by Eliminateur** [comment]
¿which klipper log analyzer are you using?, i can't see those negative temp excursions in mainsail graphs...

**Comment by kyleisah** [comment]
I'm using [Klippylyzer](https://klippylyzer.github.io/)
