### ISSUE TITLE
Weird output

### ISSUE THREAD

**Issue by Vravinite** [kyleisah/Klipper-Adaptive-Meshing-Purging#226]
**Describe the issue**
The bed mesh generated is terribly weird, it has a form of stretched triangles

**What slicer are you using?**
OrcaSlicer

**Troubleshooting**
I reinstalled KAMP and nothing else as I have NO idea what could it be

**Screenshots**
![image](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/assets/13398460/4460addf-78f3-4799-bfa5-43db3eea620c)

**Klipper log file:**
[LOG](https://uao-my.sharepoint.com/:t:/g/personal/juan_jos_cardenas_uao_edu_co/EReKtMU9mt9GjKnnb5nMc7gBDq8ql_4uJ2HZynLEgXQt1Q?e=Qryv97)

**Sliced Gcode**
[GCode](https://uao-my.sharepoint.com/:u:/g/personal/juan_jos_cardenas_uao_edu_co/EbU3Mq16BF5En6Wp2yj0YPQBGruKv2-xgMelhr60E6LUqQ?e=bdPABN)

**Additional context**
Uh IDK

**Comment by kyleisah** [comment]
All KAMP does it adjust the bounds of the mesh, not anything that would cause this. Frankly I've got no idea what could be causing a mesh like this.
