### ISSUE TITLE
adaptive mesh maybe not compatible?

### ISSUE THREAD

**Issue by Kevincondor** [kyleisah/Klipper-Adaptive-Meshing-Purging#23]
i'm fixing a btt harukan for a friend,and everything seems fine,but slicing with cura,with m117 at the top, scripts in printer.cfg and moonraker, the code dosent get injected

**Comment by Kevincondor** [comment]
ok,idk what i have done,but issuing a sudo reboot fixed the problem XD

**Comment by kyleisah** [comment]
Good to hear! I will go ahead and close this.
