### ISSUE TITLE
Do not use adaptive purge on Ender3D (S1?) with probe!

### ISSUE THREAD

**Issue by mnorrsken** [kyleisah/Klipper-Adaptive-Meshing-Purging#25]
Can you add a warning to not use the adaptive purge script on ender with BL touch. The purge logo got so thick that it hit my probe on the first layer, and with petg it would have stuck a big blob on the nozzle.

**Comment by kyleisah** [comment]
There are provisions within the macro to adjust parameters of the purge. You can reduce amount extruded to make it purge much less material.
