### ISSUE TITLE
Adaptive purge trigger max_extrude_cross_section error

### ISSUE THREAD

**Issue by allenrowand** [kyleisah/Klipper-Adaptive-Meshing-Purging#3]
When I tried to run the adaptive purge my print stopped and Mainsail warned that I exceeded the max extrude cross section; 4.1 was requested, the limit is .64. I was able to get purge working by adding max_extrude_cross_section: 5 to my config.

If the value needs to be bumped up you might want to call it out in the docs. Thanks for the code, it's pretty cool!

<img width="93" alt="CleanShot 2022-11-22 at 13 26 12@2x" src="https://user-images.githubusercontent.com/32688520/203424333-c93ce83d-b0b0-491d-adc2-b2e4a58c862a.png">

**Comment by kyleisah** [comment]
![image](https://user-images.githubusercontent.com/40312912/203452424-32c9715e-e3d5-4483-8124-0dfd4c993bf3.png)

Ah yeah haha, that'll happen. It is called out in the config file, but I think adding it somewhere in the main Readme would be beneficial.

**Comment by allenrowand** [comment]
I looked straight at it but didn't see it. Doh! Sorry.

**Comment by kyleisah** [comment]
Added some notes to the readme. Thank you!
