### ISSUE TITLE
Problem with Bed meshing

### ISSUE THREAD

**Issue by rmilyard** [kyleisah/Klipper-Adaptive-Meshing-Purging#33]
I am trying to get KAMP setup.  When I do bed mesh it is meshing whole bed not just where print is.  Trying to print voron cube.  I am followinf video from West3D.

**Comment by kyleisah** [comment]
Hey there! Could you include a gcode file from your printer and a klipper log file?

**Comment by kyleisah** [comment]
Not enough information from user
