### ISSUE TITLE
Adaptive Line Purge - line start Y position can go negative

### ISSUE THREAD

**Issue by 310weber** [kyleisah/Klipper-Adaptive-Meshing-Purging#37]
In Line_Purge.cfg

In the case where printed objects are close to the edge of the bed (`y_origin` is less than `distance_to_object_y`), the start of the purge line can be outside the bed.  `G0 X{x_origin} Y{y_origin - distance_to_object_y}` will attempt a move to a negative Y coordinate.

Suggest replacing `{% set y_origin = ([y_origin, 0] | max) %}` with
`{% set y_origin = ([(y_origin - distance_to_object), 0] | max) %}`

And replacing `G0 X{x_origin} Y{y_origin - distance_to_object_y}` with
`G0 X{x_origin} Y{y_origin}`

**Comment by kyleisah** [comment]
I have a better solution in mind and it will be implemented in the next release. I suggest lowering the distance value or setting it to 0 in the meantime, or using a different purge. Sorry for the headache!
