### ISSUE TITLE
Change working directory?

### ISSUE THREAD

**Issue by Doogle03** [kyleisah/Klipper-Adaptive-Meshing-Purging#38]
Any chance of having a separate file that has variables outside of the main config folder?  Macro itself is fine, just wondering if it's possible to use an adaptive mesh without Mainsail thinking part of the printer configuration has changed because the .cfg file has a new modified date after a different total of probe points gets calculated.

Just a vanity request, make things prettier...

**Comment by kyleisah** [comment]
This is being worked on currently and will be in a future release. 😄

**Comment by kyleisah** [comment]
I am just closing this now since it is a request, and not an issue. It is being worked on in the dev branch though
