### ISSUE TITLE
adaptive mash not adapting

### ISSUE THREAD

**Issue by shirroid** [kyleisah/Klipper-Adaptive-Meshing-Purging#4]
I am trying to run the code and it's working fine but it doesn't adapt to what I am printing. It meshes the whole bed even when I only print in the needle. The same is true for adaptive purge too.
exclude objects is enabled in the config and the slicer.

**Comment by kyleisah** [comment]
Hey there! Are you getting a readout saying something like "0 points, clamping to bed mesh"? There is a fix for this located at the bottom of the repo under Troubleshooting.

**Comment by Cliff-333** [comment]
I was about to comment on this to say I was also having this issue but after adding the M117 to the beginning of my start gcode, it is working. I wasn't originally looking for the error in the console because I (incorrectly) thought the error would cancel the print. Thanks for your work on this, @kyleisah.

**Comment by kyleisah** [comment]
@Cliff-333 can you please upload your Klipper log file here?

**Comment by shirroid** [comment]
I succeeded in resolving the issue thank you very much

**Comment by Cliff-333** [comment]
Here is my klipper log file
[klippy.log](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/files/10099105/klippy.log)

**Comment by kyleisah** [comment]
@Cliff-333 Hmmm, this all seems to be okay. Can you upload the gcode file that was giving you issues on the 2.4?

**Comment by Cliff-333** [comment]
Sure. Here is the gcode. Github wouldn't let me upload it as a .gcode file so I had to zip it.
[Cali-Dragon_v1.zip](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/files/10099148/Cali-Dragon_v1.zip)

**Comment by kyleisah** [comment]
<img width="423" alt="image" src="https://user-images.githubusercontent.com/40312912/204158808-dbd245a2-4acb-4f55-849b-14127c55dd5e.png">

Seems like for whatever reason, exclude_object is not processing your gcode files on your 2.4. This happened to me before. I had to pretty much nuke my moonraker installation and reinstall it to fix it. Before you do that though, double check you're labeling objects in the slicer and also have `[exclude_object]` in your printer.cfg and have the gcode processing bit in your moonraker.conf file. Let me know what you find!

**Comment by Cliff-333** [comment]
Yeah, I have all of those prerequisites. I guess I'll try reinstalling moonraker and will report back.

![Label objects](https://user-images.githubusercontent.com/103337290/204159182-6664a9c7-19e5-49e6-9044-dd53df4ca387.png)
![exclude object](https://user-images.githubusercontent.com/103337290/204159183-1f5c7b2a-58a7-41a9-8149-0f8e60e203ec.png)
![enable object processing](https://user-images.githubusercontent.com/103337290/204159184-f642db82-1c55-43dd-95e8-2d3a9e79c516.png)

**Comment by kyleisah** [comment]
Once you reinstall moonraker, you'll have to reupload the gcode to confirm, it doesn't process them recursively unfortunately

**Comment by Cliff-333** [comment]
Reinstalling moonraker did the trick. Adaptive mesh and purge are now working. Thanks so much for your help!
