### ISSUE TITLE
Marco Parameters

### ISSUE THREAD

**Issue by KiwiChrist** [kyleisah/Klipper-Adaptive-Meshing-Purging#41]
1. Whatever figure I enter into the 'setup purge line' parameters marco and 'send' nothing changes. Am I using it correctly?

![Screenshot from 2023-03-08 08-08-34](https://user-images.githubusercontent.com/20054687/223525856-02bb76f5-7299-4090-9b70-36e50ffa0615.png)

2. The 'purge line.cfg' varaiables do not seem to adjust the purge line print when altering them. When adjusting should they not adjust the purge line print position at least? 

![Screenshot from 2023-03-08 08-11-31](https://user-images.githubusercontent.com/20054687/223526720-c89809f8-b46e-40e1-b80a-c0751c97775f.png)

Typically I have followed the install instructions and altered the variables as nessary but not receiving any results. I am wondering if I am using this correctly.

**Comment by KiwiChrist** [comment]
I have worked it out reading the instructions again and tinkering.

**Comment by kyleisah** [comment]
Those parameters do not display changes during runtime. Once you set them, they are set until you restart. This is how it is for those using the moonraker updater installation method.
