### ISSUE TITLE
Jinja error when trying to print Gcode from Cura 5.3

### ISSUE THREAD

**Issue by gillesguillemin** [kyleisah/Klipper-Adaptive-Meshing-Purging#42]
I'm getting this error in Klipper's log:
```
!! Error evaluating 'gcode_macro BED_MESH_CALIBRATE:gcode': jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'polygon'
```
Where it gets weird, is that this happens with Gcode generated by Cura 5.3. No such problem with 5.2 (or even 5.3 Christmas alpha). I saw this too with the recent 5.3 beta but thought that was some kink needing ironing out but now 5.3 final is out and the problem remains.

**Comment by gillesguillemin** [comment]
Oh and this happens whichever model I throw at it.

**Comment by kg6ebj** [comment]
I backdated Cura to 5.2.2 to resolve the issue and have it co-installed with 5.3.0, which will not work because of the error.

Error evaluating 'gcode_macro BED_MESH_CALIBRATE:gcode': jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'polygon'

**Comment by kyleisah** [comment]
@kg6ebj 
<img width="1046" alt="image" src="https://user-images.githubusercontent.com/40312912/223622357-d2b3184a-0d16-46fb-ab45-ed762035b5db.png">
Seems like cura for whatever reason is generating an object named "nomesh" without a polygon definition. This isn't a problem with KAMP, but a problem with Cura, or how you have Cura 5.3 configured

**Comment by gillesguillemin** [comment]
And it had been flagged on the Cura repo actually. I missed that yesterday when I opened this one.

https://github.com/Ultimaker/Cura/issues/14679

**Comment by kg6ebj** [comment]
> @kg6ebj
> <img alt="image" width="1046" src="https://user-images.githubusercontent.com/40312912/223622357-d2b3184a-0d16-46fb-ab45-ed762035b5db.png">
> Seems like cura for whatever reason is generating an object named "nomesh" without a polygon definition. This isn't a problem with KAMP, but a problem with Cura, or how you have Cura 5.3 configured

There is a typo in Cura's code.
If you just replace NOMESH

Cura -> Menu -> Extensions -> Post Processing -> Modify GCode

Then Add a Script -> Search and Replace
Search is NOMESH
Replace is NONMESH

It resolves this issue
