### ISSUE TITLE
Adaptive mesh only clamping on one AXIS

### ISSUE THREAD

**Issue by DrDrache** [kyleisah/Klipper-Adaptive-Meshing-Purging#44]
Printer : Voron 2.4 - recore A6 - Voron Tap
slicer : PS 2.6-alpha5

as the title states, the adaptive mesh is only clamping on a single axis - as seen here :

Object bounds, clamped to the bed_mesh: (40.0, 40.0), (310.0, 310.0)
0 object points, clamping to bed mesh [(40.0, 40.0) (310.0, 310.0)]

attached is printer.cfg - and klippy.log

I don't know if this was because of a move to PS - or a move to newer KAMP (was using a "older" version before I updated to the current) or both?

I attempted to add the M117 line - but not sure I did that right. 
start print - and screenies for people who don't have the time to read/extract the configs :
[include Adaptive_Mesh.cfg] - direct copy from this GitHub
[include Voron_Purge.cfg] - same as above

![image](https://user-images.githubusercontent.com/774182/224728430-268f8e72-7b64-47b5-8ef3-eda3759b484f.png)
![image](https://user-images.githubusercontent.com/774182/224728939-c31f7c83-fade-41c1-8b18-0e6b8e9d27c8.png)
![image](https://user-images.githubusercontent.com/774182/224837200-abfd706d-dd4a-460b-b7d7-ffaf68cf67b9.png)
![image](https://user-images.githubusercontent.com/774182/224729276-144b2389-9be8-45a1-907d-302e3d19b06b.png)
![image](https://user-images.githubusercontent.com/774182/224729489-5261edfd-4ca0-49b0-839c-65dec38c1799.png)

[v24-configs.zip](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/files/10958256/v24-configs.zip)

EDITED  to fix screenshot of slicer.

**Comment by kyleisah** [comment]
0 object points means that Klipper is not detecting any excludable objects, something isn't correct with your setup. If you have gone through the setup correctly, and it's still not working, you likely need to repair your moonraker installation because the object processor is not working correctly.

**Comment by AxMod3DPrint** [comment]
Random question @DrDrache are you running a probe such as Klicky or the like? I've 2 printers running KAMP and after a bit of checking with someone on the Voron Discord and a fresh install of Klipper/Moonraker/Fluidd, it seems something isn't processing properly when running a Klicky probe but works fine with an inductive. This is both uploading manually and via Superslicer.

**Comment by kyleisah** [comment]
@AxMod3DPrint That has nothing to do with KAMP. Inductive uses the **default** bed_mesh_calibrate command typically. Klicky has it's own version of bed_mesh_calibrate for **attaching the probe**. Both of which, KAMP would replace by overwriting the default macro, or commenting out klicky's macro, and then calling the attach probe command from KAMP's `attach_macro` variable.

**Comment by AxMod3DPrint** [comment]
I realise that. Something is causing KAMP not to clamp to the parts in the GCode. The only difference between the two I have set up is Klicky. They were both installed the same way (kiauh) and everything is sliced the same way with the same settings. This is why I asked. I'm only trying to eliminate potential factors that could be causing this. 

Moonraker _is_ processing but Klipper isn't picking up the objects (exclude object button is greyed out) which in turn is stopping KAMP from clamping.

**Comment by kyleisah** [comment]
> I realise that. Something is causing KAMP not to clamp to the parts in the GCode. The only difference between the two I have set up is Klicky. They were both installed the same way (kiauh) and everything is sliced the same way with the same settings. This is why I asked. I'm only trying to eliminate potential factors that could be causing this.
> 
> Moonraker _is_ processing but Klipper isn't picking up the objects (exclude object button is greyed out) which in turn is stopping KAMP from clamping.

See: https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/issues/44#issuecomment-1522848328

**Comment by AxMod3DPrint** [comment]
Nope. eliminated that variable, did a fresh install using kiauh, full SD Card wipe, which the other printer was installed with and works fine.
