### ISSUE TITLE
Polygon attribute error running bed_mesh_calibrate

### ISSUE THREAD

**Issue by EklDuderino** [kyleisah/Klipper-Adaptive-Meshing-Purging#46]
Having an issue when the gcode_macro BED_MESH_CALIBRATE runs. It returns the attached error. Sliced in cura 5.3.0. Looks like something is not getting passed along properly from Cura to the printer regarding exclude_object, but I am unsure how to resolve this. Thank you.
![error455](https://user-images.githubusercontent.com/125110007/225531729-22ef1986-f57f-47e0-a61c-de3b8c0337fe.PNG)

**Comment by EklDuderino** [comment]
Found solution to this issue. Seems to be 5.3 Cura bug. https://github.com/Ultimaker/Cura/issues/14679

**Comment by kyleisah** [comment]
Thanks for bringing this to my attention! Seeing as it is a Cura bug, I am going to be closing this issue for now.
