### ISSUE TITLE
Can I use this with sonic pad? 

### ISSUE THREAD

**Issue by Savijen** [kyleisah/Klipper-Adaptive-Meshing-Purging#50]
Just ordered one and this project sounds great. Will I be able to use it or is it just for native klipper installs?

**Comment by kyleisah** [comment]
I actually don't know for sure, but I imagine it does. If you are able to `ssh` into the sonic pad, I imagine you can do just about anything.

**Comment by kyleisah** [comment]
@Savijen any updates on this? You've got me curious 😅

**Comment by Savijen** [comment]
I have not tried. You can get root on it and ssh but apparently it's very limited what you can do. Since I just received it and am still getting things tweaked to perfection, I have not had a chance to play with this....
 Yet...

**Comment by JamesH1978** [comment]
no, sonic pad has no exclude/cancel print functionality

Thanks
James

**Comment by kyleisah** [comment]
> no, sonic pad has no exclude/cancel print functionality
> 
> 
> 
> Thanks
> 
> James

Does sonic pad run a fork of an old version of klipper or something?

**Comment by JamesH1978** [comment]
yes they forked an old version of klipper, then closed their source code.

**Comment by kyleisah** [comment]
I am going to close this issue for now, as it is not a KAMP problem. I am still curious if it works on the sonic pad, but from the little information I can find, I can't confirm anything. Thank you!
