### ISSUE TITLE
Adaptive Mesh not accounting for probe offset

### ISSUE THREAD

**Issue by AxMod3DPrint** [kyleisah/Klipper-Adaptive-Meshing-Purging#55]
Hi,

I've just installed this and when probing, it doesn't seem to account my X offset of -40.3, I'm not too sure about Y due to probing being in the middle of the bed. 

Instead of having the probe go where the print is, it is probing where the nozzle is, with an effective 0 offset.  Label objects is on in the slicer (SuperSlicer) and Moonraker and my printer cfg files are set up correctly. 

See [here](https://youtu.be/giCS-HMuuUw) for a video of the issue

Output in Console:
```// led_enable : 0
00:28:45 
// status_macro: 'status_meshing'
00:28:45 
// fuzz_enable : 0
00:28:45 
// fuzz_min : 0.000000
00:28:45 
// fuzz_max : 4.000000
00:28:45 
// probe_dock_enable: 0
00:28:45 
// attach_macro: 'Attach_Probe'
00:28:45 
// detach_macro: 'Dock_Probe'
00:28:45 
// 4 object points, clamping to bed mesh [(-61.7, -9.5) (120.0, 185.0)]
00:28:45 
// Object bounds, clamped to the bed_mesh: (80.189, 94.688), (120.0, 125.312)
00:28:45 
// Algorithm: lagrange
00:28:45 
// Points: x: 3, y: 3
00:28:45 
// Generating new points...
00:28:45 
// bed_mesh: generated points
// Index | Tool Adjusted | Probe
00:28:45 
// 0 | (120.5, 104.2) | (80.2, 94.7)
00:28:45 
// 1 | (140.4, 104.2) | (100.1, 94.7)
00:28:45 
// 2 | (160.3, 104.2) | (120.0, 94.7)
00:28:45 
// 3 | (160.3, 119.5) | (120.0, 110.0)
00:28:45 
// 4 | (140.4, 119.5) | (100.1, 110.0)
00:28:45 
// 5 | (120.5, 119.5) | (80.2, 110.0)
00:28:45 
// 6 | (120.5, 134.8) | (80.2, 125.3)
00:28:45 
// 7 | (140.4, 134.8) | (100.1, 125.3)
00:28:45 
// 8 | (160.3, 134.8) | (120.0, 125.3)
```

GCode:
[3DBenchy.zip](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/files/11240892/3DBenchy.zip)

**Comment by kyleisah** [comment]
I think there's something wrong with your [probe] config. KAMP doesn't change offsets or anything like that, it just changes the min/max or the default bed mesh and adjusts points. Can you share your [probe] section?

**Comment by kyleisah** [comment]
`// 4 object points, clamping to bed mesh [(-61.7, -9.5) (120.0, 185.0)]` this is also strange. The min point here is -61.7

**Comment by AxMod3DPrint** [comment]
> I think there's something wrong with your [probe] config. KAMP doesn't change offsets or anything like that, it just changes the min/max or the default bed mesh and adjusts points. Can you share your [probe] section?

Probe section below:

```
[probe]
pin = ^!ar18
x_offset = -40.3
y_offset = -9.5
#z_offset = 0.12
samples: 3
```

Z offset is set using PROBE_CALIBRATE

**Comment by AxMod3DPrint** [comment]
> `// 4 object points, clamping to bed mesh [(-61.7, -9.5) (120.0, 185.0)]` this is also strange. The min point here is -61.7

Think I may have found where the -61.7 has come from:

```
[bed_mesh]
speed = 100
horizontal_move_z = 5
mesh_min = -61.7,-9.5
mesh_max = 120,185
probe_count = 5,5
fade_start: 1
fade_end: 10
fade_target: 0
```

I take a look at that, but I think I needed that to get the probe to probe at the edge of the bed.

**Comment by kyleisah** [comment]
I think you should maybe look into defining the origin (0,0) of your machine correctly by changing endstop positions etc. The front left corner of your bed is supposed to be 0,0. 

This tutorial is geared toward voron printers, but applies to any printer. You have to adjust values in your config so when the nozzle is at 0,0 it's over the front left corner of the bed. 

https://docs.vorondesign.com/build/startup/#define-00-point-v0-v1-trident-v2-legacy

Like I said, KAMP doesnt do anything with offsets, it just shrinks the mesh. If the points aren't probed correctly, that is because your machine isn't quite configured correctly.

**Comment by AxMod3DPrint** [comment]
The endstop positions are correct. When the printer is told to go to X0 Y0 it does. 

```
[stepper_x]
step_pin = ar54
dir_pin = ar55
enable_pin = !ar38
rotation_distance: 40
microsteps: 32
endstop_pin: ^!ar3
position_endstop = -21.5
position_min = -21.5
position_max = 220
homing_speed = 60

[stepper_y]
step_pin = ar60
dir_pin = !ar61
enable_pin = !ar56
rotation_distance: 40
microsteps: 32
endstop_pin = ^ar14
position_endstop = -6
position_min = -6
position_max = 220
homing_speed = 60
```

The probing positions are relative to the Nozzle, so therefore if I put -40.3 (- being to the right of the nozzle, + being to the left) as my probe X start, the nozzle is at X0 but the probe is 40.3mm in to the bed. I have to put the -61.7 to get the probe where it needs to be. 

Something is funky somewhere, I just can't narrow it down to this script or my config.

**Comment by kyleisah** [comment]
I think you might have those offsets flipped, the probe being to the right of the nozzle would be a positive offset, left would be a negative offset. At least, I'm pretty sure. It's been a long time since I've used offsets.

**Comment by kyleisah** [comment]
Which would actually kind of make sense because your nozzle is where your probe *should* be, so I think you've got them flipped. 😅

**Comment by AxMod3DPrint** [comment]
Yup, that's done it. The things you find when you try and make a mod...

**Comment by kyleisah** [comment]
Heh, no worries! Glad it's worked out now! Happy KAMPing! 😄
