### ISSUE TITLE
Purge Line off of Bed

### ISSUE THREAD

**Issue by LadPack** [kyleisah/Klipper-Adaptive-Meshing-Purging#57]
Hello,

When printing large objects that are either close to the size of the bed, or objects that are diagonally oriented, sometimes the purge line will be printed in the -y, spilling the purge off the side of the bed..  Is there a min/max purge area?

**Comment by LadPack** [comment]
It only occurs on my Y axis, where the minimum is -8 in my printer.cfg, is there something I should change there?

**Comment by kyleisah** [comment]
Position_max must be increased or decreased depending on where the nozzle is in relation to 0,0. 

There's a helpful guide here that goes over defining the origin of your bed (0,0) accurately. 

https://docs.vorondesign.com/build/startup/#define-00-point-v0-v1-trident-v2-legacy

**Comment by kyleisah** [comment]
This is also a very good guide here:

https://github.com/rootiest/zippy-klipper_config/blob/master/guides/GUIDE-axis_limits.md

You pretty much have to tell klipper what your correct axis limits are.

**Comment by kyleisah** [comment]
If that doesn't fix it for you, then you will have to wait until I push the next update, as this is currently being worked on in my dev branch.

**Comment by LadPack** [comment]
Thanks! I did a similar guide a while back but must have set something wrong.  I'll give it another go

**Comment by kyleisah** [comment]
@LadPack just wanted to give you an update, adding a purge_margin variable to KAMP in the next release. I've also worked out how to make it move the purge to the side of the bed if the front of the bed has no room. 😄 

<img width="1222" alt="image" src="https://user-images.githubusercontent.com/40312912/233242105-7686b15a-3899-40ef-b0d1-c91cd4df0060.png">

**Comment by LadPack** [comment]
That is awesome! Thank you for the follow up as well, keep up the good work!
