### ISSUE TITLE
Using with bltouch

### ISSUE THREAD

**Issue by gazialankus** [kyleisah/Klipper-Adaptive-Meshing-Purging#62]
Since bltouch is not mentioned anywhere, I thought I'd ask to be sure. Which of the three setup options listed here makes sense for a bltouch owner? https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging#setup 

Thanks in advance.

**Comment by david1111967** [comment]
Make the config normally validate that the variable_probe_dock_enable line is false.
And this should work

**Comment by kyleisah** [comment]
@gazialankus because the BLTouch is attached to the printhead and is not dockable, it is considered integrated.

**Comment by gazialankus** [comment]
Ok so it's this one, thank you for clarification! https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging#ive-configured-my-probe-already-or-my-probe-is-integrated
