### ISSUE TITLE
Placing the cfg files in a folder causes exception

### ISSUE THREAD

**Issue by chanders** [kyleisah/Klipper-Adaptive-Meshing-Purging#7]
I placed the CFG files in a sub folder and Klipper throws an exception.

**Comment by kyleisah** [comment]
I need more information than this. Can you share a screenshot of the exception klipper is giving?

**Comment by kyleisah** [comment]
If you are placing config files into a sub folder you need to change [include] to reflect that. 

`[include ./Macros/Adaptive_Mesh.cfg` is an example
