### ISSUE TITLE
in setup i cant find to comment out bed mesh calibrate settings

### ISSUE THREAD

**Issue by badplay** [kyleisah/Klipper-Adaptive-Meshing-Purging#70]
hi i saw  some youtube videos they told that  we  have  to comment out bed mesh  calibration if we made changes to it. but at the  readme i cant see this 

i saw it  inside  the adaptiv cfg at first line but not in the readme looks like some changes inside the readme were made ???

 EDIT i found this information under I have a dockable probe like [Klicky]
but becorse i dont have a dockable probe i wasnt looking  in maybe you can  change  the headline so all users look inside it
maybe there  are users that make changes alsow  without klicky

**Comment by kyleisah** [comment]
Typically when you have a dockable probe, you need to override your default bed mesh macro to pick up the probe first. 

The documentation is being updated, thanks!
