### ISSUE TITLE
Purge 45 degrés 

### ISSUE THREAD

**Issue by Eloura74** [kyleisah/Klipper-Adaptive-Meshing-Purging#72]
Hello everyone .  I have a problem with my adaptive purge and superslicer, when I put my part at 45 degrees the purge is no longer....adaptive....it does this at coordinates X10 and y10 approximately....ideas  ?

**Comment by kyleisah** [comment]
Turning the part 45 degrees does not remove the objects label, I don't know why that is doing that. I print parts at 45 degrees and my purge still adapts just fine. 

Check your gcode to see if EXCLUDE_OBJECT_DEFINE is being called before or after print_start.

**Comment by kyleisah** [comment]
No updates, closing
