### ISSUE TITLE
Issue when using the adaptive mesh macro

### ISSUE THREAD

**Issue by celtare21** [kyleisah/Klipper-Adaptive-Meshing-Purging#8]
Hey guys! Awesome work. I've wanted to try it too but when including the mesh macro i get the following:

Hastebin link with error: https://hastebin.com/motoraziye.apache
log:
[klippy (5).log](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/files/10111546/klippy.5.log)

**Comment by kyleisah** [comment]
Hello, I'm not sure why you're getting this issue. I haven't seen this come up before. Are you running the latest version of klipper and moonraker?

**Comment by kyleisah** [comment]
@celtare21 seems like you only have one number defined in `probe_count` and it needs to be a number for both min and max. So instead of `7`, you need to have `7,7`

**Comment by celtare21** [comment]
> @celtare21 seems like you only have one number defined in `probe_count` and it needs to be a number for both min and max. So instead of `7`, you need to have `7,7`

I can confirm this was the issue. Thank you!
