### ISSUE TITLE
margin_enable missing from  SETUP_KAMP_MESHING macro

### ISSUE THREAD

**Issue by michelegz** [kyleisah/Klipper-Adaptive-Meshing-Purging#81]
Hello, I am using KAMP via moonraker integration and I want to set **margin_enable = True**, but it is missing in SETUP_KAMP_MESHING macro.

Also, **margin_enable** is not printed in the console if **display_parameters** is enabled.

Thank you

**Comment by kyleisah** [comment]
That configuration is now deprecated, follow the instructions to set up KAMP again, it's much easier now.
