### ISSUE TITLE
Problem with Adaptive Mesh and Klicky Probe

### ISSUE THREAD

**Issue by yviccc** [kyleisah/Klipper-Adaptive-Meshing-Purging#84]
**Describe the issue**
When I run BED_MESH_CALIBRATE it simply attach then detaches the probe in sequence, I don't see any line in the code doind this
I followed every step correctly

my CFG files
[klackender.txt](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/files/11413364/klackender.txt)
[Adaptive_Mesh.txt](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/files/11413365/Adaptive_Mesh.txt)
[printer.txt](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/files/11413366/printer.txt)
[klippy.log](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/files/11413376/klippy.log)

**Comment by cryjackel** [comment]
I´ve the same problem, the BED_MESH_CLAIBRATE sent the GCODE Attach_Probe and dock_probe without doing something and then i got the "Probe triggered prior to movement" error.
If i run ATTACH_PROBE oder DOCK_PROBE its runs w/o problems.

**Comment by cryjackel** [comment]
If i attach Klicky by hand BED_MESH_CALIBRATE run with no errors but it will not dock the probe

**Comment by kyleisah** [comment]
Try updating to the newest version

**Comment by BelgarionNL** [comment]
@kyleisah you closed this but turns out I also have the same problem with the latest version. it will not grab or park the probe. I have to manually add this in my startup script: attach_probe, Detach_probe regardless if I  change your boolean in the config True for klicky probes.

**Comment by kyleisah** [comment]
You likely need to move some of your [include] calls to the TOP of printer.cfg, because KAMP is being included before the probe macros are being included or something like that.
