### ISSUE TITLE
repo marked dirty when using  moonraker update manager

### ISSUE THREAD

**Issue by vajonam** [kyleisah/Klipper-Adaptive-Meshing-Purging#9]
firstly great set of macros! 

i am using the moonraker update maanger

```
[update_manager kamp]
type: git_repo
primary_branch: main
path: ~/kamp
origin: https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging.git
```

however the repo is marked dirty because of my edits. is it feasable to add a config macro that sets up the variables inside the main macros. so those can remain clean and will cleanly update from github? 

```
[gcode_macro SETUP_KAMP]
gcode:
    SET_GCODE_VARIABLE MACRO=BED_MESH_CALIBRATE VARIABLE=variable_fuzz_enable VALUE=True
    # setup other variables
```

will this work? I can try it out, but not sure if the variables get reset what are you thoughts?

**Comment by kyleisah** [comment]
Hello, we do not currently support moonraker updating for this reason. Any changes to configs would mark it dirty, and there's not really any scripts or anything that would need to be maintained. This has come up before though, so I will look into how we can handle this.

**Comment by vajonam** [comment]
the moonraker timelapse macro uses a SETUP macro similar to above that is generated by mainsail and UI configuration for the timelapse. This is then called, so instead of editing the config files. allows us to keep the gitub as well custom configs per user. 



```
# Use _SET_TIMELAPSE_SETUP [ENABLE=value] [VERBOSE=value] [PARK_ENABLE=value] [PARK_POS=value] #
```

**Comment by kyleisah** [comment]
I have someone who may be interested in getting this to work correctly. Let me see what they come up with!

**Comment by kyleisah** [comment]
@jtrmal would you be willing to take a look? I know this is something you wanted to have working.

**Comment by jtrmal** [comment]
Gladly!

**Comment by jtrmal** [comment]
PR #32  should resolve this

**Comment by vajonam** [comment]
@jtrmal  just tried it. Trying with my klicky probe seems to fail 


```
SETUP_KAMP_MESHING DISPLAY_PARAMETERS=1 LED_ENABLE=1 FUZZ_ENABLE=1  PROBE_DOCK_ENABLE=1
SETUP_VORON_PURGE DISPLAY_PARAMETERS=1 ADAPTIVE_ENABLE=1
```

```
12:13 PM
Error evaluating 'gcode_macro BED_MESH_CALIBRATE:gcode': TypeError: 'float' object cannot be interpreted as an integer
12:13 PM
Error evaluating 'gcode_macro BED_MESH_CALIBRATE:gcode': TypeError: 'float' object cannot be interpreted as an integer
12:13 PM 16 object points, clamping to bed mesh [(40.0, 40.0) (260.0, 260.0)]
12:13 PM detach_macro: 'Dock_Probe'
12:13 PM attach_macro: 'Attach_Probe'
12:13 PM probe_dock_enable: 1
12:13 PM fuzz_max : 4.000000
12:13 PM fuzz_min : 0.000000
12:13 PM fuzz_enable : 1
12:13 PM status_macro: 'status_meshing'
12:13 PM led_enable : 1
```

removing the setup macro  and hardcoding seems to fix it. looks like something is float

**Comment by vajonam** [comment]
removing FUZZ_ENABLE=1 from my setup call seems to resolve it. something going on there.

**Comment by jtrmal** [comment]
interesting, I will try to figure it out and fix it today
y.

**Comment by jtrmal** [comment]
I don';t see anything wrong ATM, but I will try to debug it after work
y.

**Comment by vajonam** [comment]
or this

```
-        {% set fuzz_range = range(fuzz_min * 100 | int, fuzz_max * 100 | int + 1) %}
+        {% set fuzz_range = range((fuzz_min * 100) | int, (fuzz_max * 100) | int + 1) %}

```

**Comment by jtrmal** [comment]
I think the second path is more correct -- the range itself should be allowed to be float (millimeters)

**Comment by jtrmal** [comment]
do you wanna create PR? I can do it, if you don't

**Comment by vajonam** [comment]
which is the right way to do it? the parenthesis around the multiplication? or the forcing it to int on variable parsing?

**Comment by vajonam** [comment]
Yeah I can. standby

**Comment by jtrmal** [comment]
I think the second way (parentheses) and downcast to int

**Comment by kyleisah** [comment]
Thanks for the fine work dudes!

**Comment by vajonam** [comment]
just tested to update to my own PR :-) nice! this will drive more easier adoption
