### ISSUE TITLE
Purge Line

### ISSUE THREAD

**Issue by choice3d** [kyleisah/Klipper-Adaptive-Meshing-Purging#91]
I've uncommented the the purge line from the KAMP settings file and added it to the printer.cfg. But I don't get  a purge line or anything. No error messages either. Do I need I need to add something to the slicer or somewhere else? I've removed my purge line gcode from my slicer, was I not meant to do that?

I installed it all today using the newer method via ssh.

KAMP mesh works amazing btw, love it!

Cheers in advance

**Comment by kyleisah** [comment]
Are you calling the Line_Purge macro in PRINT_START?

**Comment by kyleisah** [comment]
There's also no klipper log file or anything. Those requests are in the issue template for a reason

**Comment by choice3d** [comment]
No I'm not, I guess that's it. Should I add that to the end of my start gcode

**Comment by choice3d** [comment]
Fixed and working well.

Cheers
