### ISSUE TITLE
Error evaluating 'gcode_macro BED_MESH_CALIBRATE:gcode': UndefinedError: 'dict object' has no attribute 'polygon'

### ISSUE THREAD

**Issue by Johnn201** [kyleisah/Klipper-Adaptive-Meshing-Purging#92]
**Describe the issue**
When going to print a file, or do a bed mesh calibrate I get this error: Error evaluating 'gcode_macro BED_MESH_CALIBRATE:gcode': UndefinedError: 'dict object' has no attribute 'polygon'

**What slicer are you using?** Superslicer
Prusaslicer, Superslicer, Cura, Orcaslicer...

**Troubleshooting**
What troubleshooting steps have you tried?

**Screenshots**
![Screenshot (3)](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/assets/99181507/9ce53524-1bef-4527-bdbb-78538974f451)

**Klipper log file:**
Please add klipper log fil
[klippy (1).log](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/files/11966557/klippy.1.log)
e here...

**Sliced Gcode**
Please add sliced gcode fi
[CE3PRO_Dust_Shoe_Mandrill_TOP.txt](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/files/11966759/CE3PRO_Dust_Shoe_Mandrill_TOP.txt)
le you are using here...

**Additional context**[printer.txt](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/files/11966704/printer.txt)
Add any other context about the problem here. Printed for 5 days with no problems before this using KAMP woke up the next day to start printing the error stopped me in my tracks.

**Comment by kyleisah** [comment]
It looks like your gcode preprocessor isn't taking labeled object information and making it exclude object information.

**Comment by Johnn201** [comment]
I don't understand it was working fine 1 day ago.

**Comment by kyleisah** [comment]
```gcode

; object:{"name":"Dust_Shoe_Mandrill_TOP","id":"Dust_Shoe_Mandrill_TOP.stl id:0 copy 0","object_center":[112.500000,112.500000,0.000000],"boundingbox_center":[112.500000,112.500000,17.500000],"boundingbox_size":[115.980335,68.827911,35.000000]}
; plater:{"center":[112.500000,112.500000,0.000000],"boundingbox_center":[112.500000,112.500000,17.500000],"boundingbox_size":[115.980335,68.827911,35.000000]}

;TYPE:Custom
G28 ; home all axes
G1 Z5 F5000 ; lift nozzle
M107
G21 ; set units to millimeters
G90 ; use absolute coordinates
; Filament gcode
M117
            M190 S0
            M109 S0
            PRINT_START EXTRUDER_TEMP=210 BED_TEMP=60  MATERIAL=PLA+ 
                        
;_TOOLCHANGE 0
```

Look, as I mentioned before, your preprocessor is not defining objects when your gcode file is uploaded. This is not a KAMP issue.

**Comment by Johnn201** [comment]
Consider helpfull advice next time like maybe this, https://github.com/kageurufu/preprocess_cancellation?search=1
