### ISSUE TITLE
Movement outside of printable area

### ISSUE THREAD

**Issue by ksummers92** [kyleisah/Klipper-Adaptive-Meshing-Purging#93]
On my V0.2, if the build plate is particularly full (but still enough room for purge), then the x_origin is set to 0, but the printer moves to a position less than 0 resulting in a print failure.

Slicer: SuperSlicer 2.5.59.2

I have tried changing the macro to set the x_origin/y_origin to 0.000 if x_origin is less than 0 in case it is a rounding error problem, but the same behavior results.

Applicable screenshot:
![image](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/assets/66363414/50edf642-7751-4026-922a-441e754dea51)

Klippy log:
[klippy (10).log](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/files/11968241/klippy.10.log)

Sliced GCode:
[side_strap_x4.zip](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/files/11968250/side_strap_x4.zip)

**Comment by TomMeyer90** [comment]
Since the last update, the Voron purge is no longer available. Will be added again later.
you must select the line purge

**Comment by ksummers92** [comment]
Ah I see. Just released yesterday. Guess I hadn’t seen the update from moonraker updater yet. Thanks!
