### ISSUE TITLE
 Unknown command:"PRINT_START" and Unknown command:"MESH_CONFIG"

### ISSUE THREAD

**Issue by Elchschmied** [kyleisah/Klipper-Adaptive-Meshing-Purging#95]
**Describe the issue**
Startgcode no longer works. Leveling isn't done. No heating of extruder and bed.

**What slicer are you using?**
Prusaslicer

**Troubleshooting**
I installed old macros and that works.
The new includes are made.
![grafik](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/assets/129211492/43333900-7864-4b37-8f48-dcb6db6eca9c)

**Screenshots**
![grafik](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/assets/129211492/7b69d625-ef56-40d6-a8ad-2cd6889ae34e)
![grafik](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/assets/129211492/04ebdd21-061c-41b1-b2ba-810e36ae2d93)

**Klipper log file:**
[klippy(7).log](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/files/11970482/klippy.7.log)

**Sliced Gcode**
[Webshooter_Marlon_0.15mm_PLA_Ulticlone_Klipper_1h24m.zip](https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging/files/11970506/Webshooter_Marlon_0.15mm_PLA_Ulticlone_Klipper_1h24m.zip)

**Additional context**
I think the manual is no longer available and that could help to use the right macros in start gcode. May be it is planned but not yet completed.

**Comment by kyleisah** [comment]
MESH_CONFIG is not a macro in KAMP.

**Comment by kkberg** [comment]
Sorry, this were the macros from last Version but I don‘t see a manual for the new commands. How do I have to procede with the new version? This Information is still missing.

**Comment by Elchschmied** [comment]
okay, got it how to use. To easy for me, sorry.
